<a href="https://colab.research.google.com/github/HanifCahyo/pertemuan3DataMiningPreprocessingData/blob/main/ProcessingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Buat import library yang dibutuhkan

In [1]:
# Numpy merupakan library yang digunakan untuk operasi matriks dan array
import numpy as np

# Matplotlib merupakan library yang digunakan untuk visualisasi data
import matplotlib.pyplot as plt

# Pandas merupakan library yang digunakan untuk manipulasi data
import pandas as pd

# Scikit-learn merupakan library yang digunakan untuk machine learning
import sklearn as sk


Untuk Mengambil data dari file "data - copy.csv"

In [3]:
dataset = pd.read_csv("Data - Copy.csv")  # Membaca file csv
x = dataset.iloc[:, :-1].values  # Mengambil semua data kecuali kolom terakhir
y = dataset.iloc[:, -1].values  # Mengambil kolom terakhir
print(x)
print(y)

[['PNS' 27.0 nan]
 ['Guru' nan 4800000.0]
 ['Dosen' 53.0 nan]
 ['PNS' 45.0 5000000.0]
 ['Buruh' 47.0 1900000.0]
 ['Guru' nan 5800000.0]
 ['Dosen' 32.0 nan]
 ['Buruh' nan 3500000.0]
 ['Polisi' 29.0 8300000.0]
 ['Tentara' nan nan]]
['No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes']


menambahkan nilai nan dengan mean rata rata

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['PNS' 27.0 4883333.333333333]
 ['Guru' 38.833333333333336 4800000.0]
 ['Dosen' 53.0 4883333.333333333]
 ['PNS' 45.0 5000000.0]
 ['Buruh' 47.0 1900000.0]
 ['Guru' 38.833333333333336 5800000.0]
 ['Dosen' 32.0 4883333.333333333]
 ['Buruh' 38.833333333333336 3500000.0]
 ['Polisi' 29.0 8300000.0]
 ['Tentara' 38.833333333333336 4883333.333333333]]


merubah string menjadi numerikal ex : PNS menjadi 1.0 0.0 0.0 0.0 1.0 0.0 0.0

In [7]:
from sklearn.compose import (
    ColumnTransformer,
)  # ColumnTransformer untuk mengubah data kategorikal menjadi numerikal
from sklearn.preprocessing import (
    OneHotEncoder,
)  # OneHotEncoder untuk mengubah data kategorikal menjadi numerikal

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough"
)  # OneHotEncoder untuk mengubah data kategorikal menjadi numerikal

x = np.array(ct.fit_transform(x))  # Mengubah data kategorikal menjadi numerikal
print(x)

[[1.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 4883333.333333333]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 38.833333333333336 4800000.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 53.0 4883333.333333333]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 45.0 5000000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 47.0 1900000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 38.833333333333336 5800000.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 32.0 4883333.333333333]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 38.833333333333336 3500000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 29.0 8300000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 38.833333333333336 4883333.333333333]]


menambahkan kolom label pada data dengan nilai 1 atau 0

In [8]:
from sklearn.preprocessing import (
    LabelEncoder,
)  # LabelEncoder untuk mengubah data kategorikal menjadi numerikal

le = LabelEncoder()  # LabelEncoder untuk mengubah data kategorikal menjadi numerikal
y = le.fit_transform(y)  # Mengubah data kategorikal menjadi numerikal
print(y)  # Menampilkan data y

[0 1 0 1 0 0 0 1 0 1]


In [9]:
from sklearn.model_selection import (
    train_test_split,
)  # train_test_split untuk membagi data menjadi data training dan data testing

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=1
)  # Memisahkan data menjadi data training dan data testing

mendapatkan data x train 80% dari kapasitas

In [10]:
print(x_train)  # Menampilkan data x_train

[[1.0 0.0 1.0 0.0 0.0 0.0 0.0 32.0 4883333.333333333]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 47.0 1900000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 4883333.333333333]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 45.0 5000000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 38.833333333333336 4800000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 38.833333333333336 3500000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 29.0 8300000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 38.833333333333336 5800000.0]]


mendapatkan data x test 20% dari kapasitas

In [11]:
print(x_test)  # Menampilkan data x_test

[[1.0 0.0 1.0 0.0 0.0 0.0 0.0 53.0 4883333.333333333]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 38.833333333333336 4883333.333333333]]


mendapatkan data y train 80 persen

In [12]:
print(y_train)  # Menampilkan data y_train

[0 0 0 1 1 1 0 0]


mendapatkan data y test 20 persen dari kapasitas

In [ ]:
print(y_test)  # Menampilkan data y_test

melakukan distribusi pada kolom umur dan pendapatan

In [14]:
from sklearn.preprocessing import (
    StandardScaler,
)  # StandardScaler untuk mengubah data menjadi data yang berdistribusi normal

sc = (
    StandardScaler()
)  # StandardScaler untuk mengubah data menjadi data yang berdistribusi normal
x_train[:, 3:] = sc.fit_transform(
    x_train[:, 3:]
)  # Mengubah data menjadi data yang berdistribusi normal
x_test[:, 3:] = sc.transform(
    x_test[:, 3:]
)  # Mengubah data menjadi data yang berdistribusi normal

menampilkan kolom pekerjaan, umur, pendapatan

In [15]:
print(x_train)  # Menampilkan data x_train
print(x_test)  # Menampilkan data x_test

[[1.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 -0.3779644730092272
  0.0 -0.7514940789148868 -1.8041124150158794e-16]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.3779644730092272
  0.0 1.4751550437958885 -1.7462999100741547]
 [1.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 -0.3779644730092272
  0.0 -1.4937104531518122 -1.8041124150158794e-16]
 [1.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 -0.3779644730092272
  0.0 1.1782684941011186 0.0682910579358608]
 [1.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.3779644730092272
  0.0 0.26286829920891125 -0.048779327097043426]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.3779644730092272
  0.0 0.26286829920891125 -0.8097368298109209]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 2.6457513110645907
  0.0 -1.196823903457042 1.9999524109787805]
 [1.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.3779644730092272
  0.0 0.26286829920891125 0.5365725980674777]]
[[1.0 0.0 1.0 -0.577350269189625

mendapatkan kolom label ya atau tidak

In [16]:
print(y_train)  # Menampilkan data y_train
print(y_test)  # Menampilkan data y_test

[0 0 0 1 1 1 0 0]
[0 1]
